"use client";

import { useState, useMemo } from "react";
import { CopyIcon, CheckIcon, DownloadIcon, CalculatorIcon } from "lucide-react";

interface ModelPricing {
  id: string;
  name: string;
  provider: string;
  inputCostPer1M: number;
  outputCostPer1M: number;
}

const PRICING_MATRIX: ModelPricing[] = [
  { id: "gpt-4o", name: "GPT-4o", provider: "OpenAI", inputCostPer1M: 5.0, outputCostPer1M: 15.0 },
  { id: "gpt-4o-mini", name: "GPT-4o-mini", provider: "OpenAI", inputCostPer1M: 0.15, outputCostPer1M: 0.6 },
  { id: "claude-3-5-sonnet", name: "Claude 3.5 Sonnet", provider: "Anthropic", inputCostPer1M: 3.0, outputCostPer1M: 15.0 },
  { id: "claude-3-haiku", name: "Claude 3 Haiku", provider: "Anthropic", inputCostPer1M: 0.25, outputCostPer1M: 1.25 },
  { id: "gemini-1-5-pro", name: "Gemini 1.5 Pro", provider: "Google", inputCostPer1M: 3.5, outputCostPer1M: 10.5 },
  { id: "gemini-1-5-flash", name: "Gemini 1.5 Flash", provider: "Google", inputCostPer1M: 0.075, outputCostPer1M: 0.3 },
  { id: "llama-3-1-70b", name: "Llama 3.1 70B (Hosted)", provider: "Open Source", inputCostPer1M: 0.6, outputCostPer1M: 0.9 },
];

export function LlmCostCalculator() {
  const [promptTokens, setPromptTokens] = useState<number>(1000);
  const [completionTokens, setCompletionTokens] = useState<number>(500);
  const [monthlyRequests, setMonthlyRequests] = useState<number>(100000);
  const [copied, setCopied] = useState(false);

  const calculations = useMemo(() => {
    return PRICING_MATRIX.map((model) => {
      const inputCostPerReq = (promptTokens / 1_000_000) * model.inputCostPer1M;
      const outputCostPerReq = (completionTokens / 1_000_000) * model.outputCostPer1M;
      const totalCostPerReq = inputCostPerReq + outputCostPerReq;
      const costPer1k = totalCostPerReq * 1000;
      const monthlyTotal = totalCostPerReq * monthlyRequests;

      return {
        ...model,
        totalCostPerReq,
        costPer1k,
        monthlyTotal,
      };
    }).sort((a, b) => a.monthlyTotal - b.monthlyTotal);
  }, [promptTokens, completionTokens, monthlyRequests]);

  const handleCopySummary = () => {
    const summary = calculations.map((c, i) => 
      `${i + 1}. ${c.name} (${c.provider})\n   Monthly Cost: $${c.monthlyTotal.toFixed(2)}\n   Cost per 1k requests: $${c.costPer1k.toFixed(4)}`
    ).join("\n\n");
    
    const text = `LLM Cost Estimate\nTokens: ${promptTokens} In / ${completionTokens} Out\nRequests: ${monthlyRequests.toLocaleString()}/mo\n\n${summary}`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadJson = () => {
    const blob = new Blob([JSON.stringify(calculations, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "llm-cost-estimation.json";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const formatCurrency = (val: number, minimumFractionDigits = 2) => {
    return new Intl.NumberFormat("en-US", {
      style: "currency",
      currency: "USD",
      minimumFractionDigits,
      maximumFractionDigits: 4,
    }).format(val);
  };

  return (
    <div className="grid lg:grid-cols-12 gap-8 items-start w-full">
      {/* Controls */}
      <div className="lg:col-span-4 card p-6 bg-card/60 shadow-sm border-line/40 space-y-6">
        <div>
          <label className="field-label block text-sm font-bold text-fg mb-2">Prompt Tokens (Input)</label>
          <input 
            type="number" min="1" step="100"
            className="input w-full bg-field border-line focus:border-accent"
            value={promptTokens}
            onChange={(e) => setPromptTokens(parseInt(e.target.value) || 0)}
          />
          <p className="text-xs text-muted mt-1">Average tokens sent to the model per request.</p>
        </div>
        <div>
          <label className="field-label block text-sm font-bold text-fg mb-2">Completion Tokens (Output)</label>
          <input 
            type="number" min="1" step="100"
            className="input w-full bg-field border-line focus:border-accent"
            value={completionTokens}
            onChange={(e) => setCompletionTokens(parseInt(e.target.value) || 0)}
          />
          <p className="text-xs text-muted mt-1">Average tokens generated by the model.</p>
        </div>
        <div>
          <label className="field-label block text-sm font-bold text-fg mb-2">Monthly Requests</label>
          <select 
            className="input w-full bg-field border-line focus:border-accent"
            value={monthlyRequests}
            onChange={(e) => setMonthlyRequests(parseInt(e.target.value))}
          >
            <option value="1000">1,000 requests</option>
            <option value="10000">10,000 requests</option>
            <option value="100000">100,000 requests</option>
            <option value="1000000">1,000,000 requests</option>
            <option value="10000000">10,000,000 requests</option>
          </select>
        </div>

        <div className="border-t border-line/40 pt-4 mt-6">
          <button onClick={handleCopySummary} className="btn btn-primary w-full flex justify-center items-center gap-2 mb-3">
            {copied ? <CheckIcon className="w-4 h-4" /> : <CopyIcon className="w-4 h-4" />}
            {copied ? "Copied Summary!" : "Copy Summary Report"}
          </button>
          <button onClick={handleDownloadJson} className="btn btn-secondary w-full flex justify-center items-center gap-2">
            <DownloadIcon className="w-4 h-4" /> Export as JSON
          </button>
        </div>
      </div>

      {/* Results Matrix */}
      <div className="lg:col-span-8 flex flex-col gap-4">
        {calculations.map((calc, idx) => (
          <div key={calc.id} className="card p-5 bg-card/40 border-line/30 flex flex-col sm:flex-row sm:items-center justify-between gap-4 transition-all hover:border-accent/40 hover:shadow-md">
            <div className="flex items-start gap-4">
              <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-hover/80 text-accent font-bold">
                #{idx + 1}
              </div>
              <div>
                <h3 className="text-base font-bold text-fg">{calc.name}</h3>
                <p className="text-xs font-medium text-muted">{calc.provider}</p>
                <div className="mt-2 text-xs text-muted flex gap-3">
                  <span>Input: ${calc.inputCostPer1M}/1M</span>
                  <span>Output: ${calc.outputCostPer1M}/1M</span>
                </div>
              </div>
            </div>
            <div className="flex flex-row sm:flex-col items-center sm:items-end justify-between sm:justify-center gap-2 sm:gap-1 p-3 sm:p-0 bg-field/50 sm:bg-transparent rounded-lg border border-line/40 sm:border-none">
              <div className="text-xs text-muted font-medium sm:hidden">Est. Monthly Cost</div>
              <div className="text-lg font-black text-accent tracking-tight">
                {formatCurrency(calc.monthlyTotal)}
              </div>
              <div className="text-xs text-muted font-mono">
                {formatCurrency(calc.costPer1k)} / 1k req
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
