"use client";

import { useState } from "react";
import type { AiTool } from "@/lib/ai-tools";

export function ToolForm({ tool }: { tool: AiTool }) {
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<string | null>(null);

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setLoading(true);
    // Simulate AI generation delay
    setTimeout(() => {
      setResult(`// Generated by ${tool.name}\n// Optimized configuration goes here.\n\nconsole.log("Enterprise grade code generated.");`);
      setLoading(false);
    }, 800);
  };

  return (
    <div className="grid lg:grid-cols-2 gap-8 lg:gap-12 items-start w-full">
      <div className="card p-6 sm:p-8 bg-card/60 shadow-sm border-line/40">
        <form onSubmit={handleSubmit} className="space-y-6">
          {tool.inputs.map((input) => (
            <div key={input.name}>
              <label htmlFor={input.name} className="field-label text-sm text-fg mb-1.5 block">
                {input.label}
              </label>
              {input.type === "textarea" ? (
                <textarea
                  id={input.name}
                  name={input.name}
                  className="input min-h-[120px] bg-field border-line focus:border-accent resize-y"
                  placeholder={input.placeholder}
                  required
                />
              ) : input.type === "select" ? (
                <select
                  id={input.name}
                  name={input.name}
                  className="input bg-field border-line focus:border-accent"
                  required
                >
                  {input.options?.map((opt) => (
                    <option key={opt} value={opt}>{opt}</option>
                  ))}
                </select>
              ) : (
                <input
                  type={input.type}
                  id={input.name}
                  name={input.name}
                  className="input bg-field border-line focus:border-accent"
                  placeholder={input.placeholder}
                  required
                />
              )}
            </div>
          ))}

          <button
            type="submit"
            disabled={loading}
            className="btn btn-primary w-full h-11 text-sm font-semibold flex justify-center items-center gap-2"
          >
            {loading ? (
              <span className="inline-block h-4 w-4 animate-spin rounded-full border-2 border-current border-t-transparent" />
            ) : null}
            {loading ? "Generating..." : `Generate with ${tool.name.split(" ")[0]}`}
          </button>
        </form>
      </div>

      <div className="card p-6 sm:p-8 bg-hover/30 shadow-sm border-line/30 min-h-[300px] flex flex-col h-full">
        <h3 className="text-sm font-semibold text-muted mb-4 tracking-wide uppercase">Output Console</h3>
        {result ? (
          <pre className="code-block flex-1 bg-card border-line/50 text-sm overflow-auto text-fg">
            <code>{result}</code>
          </pre>
        ) : (
          <div className="flex-1 flex flex-col items-center justify-center text-center text-muted border-2 border-dashed border-line/40 rounded-xl p-8">
            <svg className="w-8 h-8 mb-4 opacity-50" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
            </svg>
            <p className="text-sm">Your generated configuration will appear here.</p>
          </div>
        )}
      </div>
    </div>
  );
}
